//GENERATED BY WOLFETPLAYER - 05-09-19 for
//GENERATED BY WOLFETPLAYER - 05-09-19 for
//https://www.moddb.com/mods/realrtcw-realism-mod

models/weapons/shells/bullet1
{
	{
		map models/weapons/shells/bullet1.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.6 1.6
		rgbGen lightingDiffuse
        }
}

models/weapons/shells/bullet2
{
	{
		map models/weapons/shells/bullet2.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.6 1.6
		rgbGen lightingDiffuse
        }
}

// SNOOPER

models/weapons/rifles/snooper/wpn_base
{
	{
		map models/weapons/rifles/snooper/wpn_base.png
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.6 1.6
		rgbGen lightingDiffuse
        }
}

models/weapons/rifles/snooper/wpn_base_upgraded
{
	{
		map models/weapons/rifles/snooper/wpn_base.png
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.6 1.6
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/rifles/snooper/wpn_silencer
{
	{
		map models/weapons/rifles/snooper/wpn_silencer.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.6 1.6
		rgbGen lightingDiffuse
        }
}

models/weapons/rifles/snooper/wpn_silencer_upgraded
{
	{
		map models/weapons/rifles/snooper/wpn_silencer.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.6 1.6
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}



models/weapons/rifles/snooper/wpn_mag
{
	{
		map models/weapons/rifles/snooper/wpn_mag.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.6 1.6
		rgbGen lightingDiffuse
        }
}

models/weapons/rifles/snooper/wpn_mag_upgraded
{
	{
		map models/weapons/rifles/snooper/wpn_mag.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.6 1.6
		rgbGen lightingDiffuse
        }
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
		
}

models/weapons/rifles/snooper/wpn_optic
{
	{
		map models/weapons/rifles/snooper/wpn_optic.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.6 1.6
		rgbGen lightingDiffuse
        }
}

models/weapons/rifles/snooper/wpn_scope
{
	{
		map models/weapons/rifles/snooper/wpn_scope.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.6 1.6
		rgbGen lightingDiffuse
        }
}

models/weapons/rifles/snooper/wpn_scope_upgraded
{
	{
		map models/weapons/rifles/snooper/wpn_scope.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.6 1.6
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/smgs/mp34/wpn_base
{
	{
		map models/weapons/smgs/mp34/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.6 1.6
		rgbGen lightingDiffuse
        }
}

models/weapons/smgs/mp34/wpn_base_upgraded
{
	{
		map models/weapons/smgs/mp34/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.6 1.6
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/shotguns/ithaca/wpn_base
{
	{
		map models/weapons/shotguns/ithaca/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.6 1.6
		rgbGen lightingDiffuse
        }
}

models/weapons/shotguns/ithaca/wpn_base_upgraded
{
	{
		map models/weapons/shotguns/ithaca/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.6 1.6
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/shotguns/auto5/wpn_base
{
	{
		map models/weapons/shotguns/auto5/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.6 1.6
		rgbGen lightingDiffuse
        }
}

models/weapons/shotguns/auto5/wpn_base_upgraded
{
	{
		map models/weapons/shotguns/auto5/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.6 1.6
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/shotguns/auto5/wpn_stock
{
	{
		map models/weapons/shotguns/auto5/wpn_stock.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.6 1.6
		rgbGen lightingDiffuse
        }
}

models/weapons/shotguns/auto5/wpn_stock_upgraded
{
	{
		map models/weapons/shotguns/auto5/wpn_stock.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.6 1.6
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}


models/weapons/shotguns/auto5/wpn_barrel
{
	{
		map models/weapons/shotguns/auto5/wpn_barrel.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.6 1.6
		rgbGen lightingDiffuse
        }
}

models/weapons/shotguns/auto5/wpn_barrel_upgraded
{
	{
		map models/weapons/shotguns/auto5/wpn_barrel.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.6 1.6
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/rifles/mosin/wpn_base
{
	{
		map models/weapons/rifles/mosin/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .14
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/rifles/mosin/wpn_base_upgraded
{
	{
		map models/weapons/rifles/mosin/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .14
		tcGen environment
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/rifles/mosin/wpn_clip
{
	{
		map models/weapons/rifles/mosin/wpn_clip.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .14
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/rifles/mosin/wpn_clip_upgraded
{
	{
		map models/weapons/rifles/mosin/wpn_clip.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .14
		tcGen environment
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/rifles/delisle/wpn_base
{
	{
		map models/weapons/rifles/delisle/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .14
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/rifles/delisle/wpn_base_upgraded
{
	{
		map models/weapons/rifles/delisle/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .14
		tcGen environment
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/auto_rifles/m1941/wpn_base
{
	{
		map models/weapons/auto_rifles/m1941/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .14
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/auto_rifles/m1941/wpn_base_upgraded
{
	{
		map models/weapons/auto_rifles/m1941/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .14
		tcGen environment
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/auto_rifles/m1941/wpn_scope
{
	{
		map models/weapons/auto_rifles/m1941/wpn_scope.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .14
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/auto_rifles/m1941/wpn_scope_upgraded
{
	{
		map models/weapons/auto_rifles/m1941/wpn_scope.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .14
		tcGen environment
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}


models/weapons/assault_rifles/fg42/wpn_base
{
	{
		map models/weapons/assault_rifles/fg42/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .10
                tcmod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/assault_rifles/fg42/wpn_base_upgraded
{
	{
		map models/weapons/assault_rifles/fg42/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .10
                tcmod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/assault_rifles/fg42/wpn_optic
{
	{
		map models/weapons/assault_rifles/fg42/wpn_optic.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envFG.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .50
		tcGen environment
                tcMod scale 8.5 8.5
		rgbGen lightingDiffuse
        }
}

models/weapons/smgs/ppsh/wpn_base
{
	{
		map models/weapons/smgs/ppsh/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .12
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/smgs/ppsh/wpn_base_upgraded
{
	{
		map models/weapons/smgs/ppsh/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .12
		tcGen environment
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}


models/weapons/secret/venom/wpn_base
{
	{
		map models/weapons/secret/venom/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .15
                tcmod scale 1.9 1.9
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/secret/venom/wpn_base_upgraded
{
	{
		map models/weapons/secret/venom/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .15
                tcmod scale 1.9 1.9
		tcGen environment
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/secret/venom/wpn_misc
{
	{
		map models/weapons/secret/venom/wpn_misc.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .15
                tcmod scale 1.9 1.9
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/secret/venom/wpn_misc_upgraded
{
	{
		map models/weapons/secret/venom/wpn_misc.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .15
                tcmod scale 1.9 1.9
		tcGen environment
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/secret/tesla/wpn_base
{
	{
		map models/weapons/secret/tesla/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .15
                tcmod scale 1.9 1.9
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/secret/tesla/wpn_base_upgraded
{
	{
		map models/weapons/secret/tesla/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .15
                tcmod scale 1.9 1.9
		tcGen environment
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/secret/tesla/wpn_bag
{
	{
		map models/weapons/secret/tesla/wpn_bag.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .15
                tcmod scale 1.9 1.9
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/secret/tesla/wpn_bag_upgraded
{
	{
		map models/weapons/secret/tesla/wpn_bag.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .15
                tcmod scale 1.9 1.9
		tcGen environment
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/explosives/pineapple/wpn_base
{
	{
		map models/weapons/explosives/pineapple/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slate.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
				tcmod scale 1.1 1.1
		tcGen environment
		rgbGen lightingDiffuse
        }
}
models/weapons/explosives/grenade/wpn_base
{
	{
		map models/weapons/explosives/grenade/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
				tcmod scale 1.1 1.1
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/heavy/flame/wpn_base
{
	{
		map models/weapons/heavy/flame/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
				tcmod scale 1.1 1.1
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/heavy/flame/wpn_base_upgraded
{
	{
		map models/weapons/heavy/flame/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
				tcmod scale 1.1 1.1
		tcGen environment
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/heavy/flame/flame_pickup
{
	{
		map models/weapons/heavy/flame/flame_pickup.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
				tcmod scale 1.1 1.1
		tcGen environment
		rgbGen lightingDiffuse
        }
	{
		map $whiteimage
                blendFunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons/pistols/luger/wpn_base
{
	{
		map models/weapons/pistols/luger/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .10
				tcmod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/pistols/luger/wpn_base_upgraded
{
	{
		map models/weapons/pistols/luger/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .10
				tcmod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
		
		{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/pistols/luger_silenced/wpn_base
{
	{
		map models/weapons/pistols/luger_silenced/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .10
				tcmod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/pistols/luger_silenced/wpn_base_upgraded
{
	{
		map models/weapons/pistols/luger_silenced/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .10
				tcmod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
		
		{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/pistols/luger_silenced/wpn_silencer
{
	{
		map models/weapons/pistols/luger_silenced/wpn_silencer.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .10
				tcmod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/pistols/luger_silenced/wpn_silencer_upgraded
{
	{
		map models/weapons/pistols/luger_silenced/wpn_silencer.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .10
				tcmod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
		
		{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons2/c4_dynamite/dynomite1a
{
	{
		map models/weapons2/c4_dynamite/dynomite1a.tga
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .05
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/explosives/dynamite/wpn_base
{
	{
		map models/weapons/explosives/dynamite/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/rifles/mauser/wpn_clip
{
	{
		map models/weapons/rifles/mauser/wpn_clip.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
        alphaGen const .16
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/rifles/mauser/wpn_clip_upgraded
{
	{
		map models/weapons/rifles/mauser/wpn_clip.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
        alphaGen const .16
		tcGen environment
		rgbGen lightingDiffuse
        }
		
		{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/rifles/mauser/wpn_base
{
	{
		map models/weapons/rifles/mauser/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
         alphaGen const .1
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/rifles/mauser/wpn_base_upgraded
{
	{
		map models/weapons/rifles/mauser/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
         alphaGen const .1
		tcGen environment
		rgbGen lightingDiffuse
        }
		
		{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/rifles/mauser/wpn_scope
{
	{
		map models/weapons/rifles/mauser/wpn_scope.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
         alphaGen const .1
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/rifles/mauser/wpn_scope_upgraded
{
	{
		map models/weapons/rifles/mauser/wpn_scope.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
         alphaGen const .1
		tcGen environment
		rgbGen lightingDiffuse
        }
		
		{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/rifles/mauser/wpn_optic
{
	{
		map models/weapons/rifles/mauser/wpn_optic.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envFG.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .50
		tcGen environment
                tcMod scale 8.5 8.5
		rgbGen lightingDiffuse
        }
}


models/weapons/heavy/mg42/wpn_base2
{
	{
		map models/weapons/heavy/mg42/wpn_base2.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .15
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/heavy/mg42/wpn_base2_upgraded
{
	{
		map models/weapons/heavy/mg42/wpn_base2.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .15
		tcGen environment
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/heavy/mg42/wpn_mag
{
	{
		map models/weapons/heavy/mg42/wpn_mag.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .15
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/heavy/mg42/wpn_mag_upgraded
{
	{
		map models/weapons/heavy/mg42/wpn_mag.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .15
		tcGen environment
		rgbGen lightingDiffuse
        }
		
		{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}


models/mapobjects/weapons/wpn_mag
{
	{
		map models/mapobjects/weapons/wpn_mag.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .13
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/mapobjects/weapons/wpn_base2
{
	{
		map models/mapobjects/weapons/wpn_base2.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .15
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/mapobjects/weapons/wpn_base2_upgraded
{
	{
		map models/mapobjects/weapons/wpn_base2.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .15
		tcGen environment
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/heavy/mg42/wpn_base
{
	{
		map models/weapons/heavy/mg42/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .15
		tcGen environment
                tcMod scale 1.2 1.2
		rgbGen lightingDiffuse
        }
}

models/weapons/heavy/mg42/wpn_base_upgraded
{
	{
		map models/weapons/heavy/mg42/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .15
		tcGen environment
                tcMod scale 1.2 1.2
		rgbGen lightingDiffuse
        }
		
		{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/heavy/browning/wpn_base
{
	{
		map models/weapons/heavy/browning/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .15
		tcGen environment
                tcMod scale 1.2 1.2
		rgbGen lightingDiffuse
        }
}

models/weapons/heavy/browning/wpn_base_upgraded
{
	{
		map models/weapons/heavy/browning/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .15
		tcGen environment
                tcMod scale 1.2 1.2
		rgbGen lightingDiffuse
        }
		
		{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

// Knife

models/weapons/melee/knife/wpn_base
{
	{
		map models/weapons/melee/knife/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
        alphaGen const .15
		tcGen environment
        tcMod scale 1.5 1.5
		rgbGen lightingDiffuse
        }
}

models/weapons/melee/knife/wpn_base_upgraded
{
	{
		map models/weapons/melee/knife/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
        alphaGen const .15
		tcGen environment
        tcMod scale 1.5 1.5
		rgbGen lightingDiffuse
        }
		
		{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}


models/weapons/smgs/mp40/wpn_base
{
	{
		map models/weapons/smgs/mp40/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .10
                tcMod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/smgs/mp40/wpn_base_upgraded
{
	{
		map models/weapons/smgs/mp40/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	
		{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .10
                tcMod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
		
		{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/pistols/colt/wpn_base
{
	{
		map models/weapons/pistols/colt/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .15
				tcMod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/pistols/colt/wpn_base_upgraded
{
	{
		map models/weapons/pistols/colt/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	
		{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .10
                tcMod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
		
		{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}



models/weapons/pistols/hdm/wpn_base
{
	{
		map models/weapons/pistols/hdm/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .15
				tcMod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/pistols/hdm/wpn_base_upgraded
{
	{
		map models/weapons/pistols/hdm/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	
		{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .10
                tcMod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
		
		{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/pistols/revolver/wpn_base
{
	{
		map models/weapons/pistols/revolver/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .10
				tcMod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/pistols/revolver/wpn_base_upgraded
{
	{
		map models/weapons/pistols/revolver/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	
		{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .10
                tcMod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
		
		{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/assault_rifles/bar/wpn_base
{
	{
		map models/weapons/assault_rifles/bar/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .15
				tcMod scale 1.4 1.4
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/assault_rifles/bar/wpn_base_upgraded
{
	{
		map models/weapons/assault_rifles/bar/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	
		{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .10
                tcMod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
		
		{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}


models/weapons/heavy/pf/wpn_base
{
	{
		map models/weapons/heavy/pf/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .12
				tcMod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/heavy/pf/wpn_base_upgraded
{
	{
		map models/weapons/heavy/pf/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .12
				tcMod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
		
			{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}


models/weapons/auto_rifles/m1_garand/wpn_base
{
	{
		map models/weapons/auto_rifles/m1_garand/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .13
				tcMod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/auto_rifles/m1_garand/wpn_base_upgraded
{
	{
		map models/weapons/auto_rifles/m1_garand/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .13
				tcMod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/auto_rifles/m1_garand/wpn_bolt
{
	{
		map models/weapons/auto_rifles/m1_garand/wpn_bolt.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .13
				tcMod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/auto_rifles/m1_garand/wpn_bolt_upgraded
{
	{
		map models/weapons/auto_rifles/m1_garand/wpn_bolt.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .13
				tcMod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
		
			{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/auto_rifles/g43/wpn_base
{
	{
		map models/weapons/auto_rifles/g43/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .13
				tcMod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/auto_rifles/g43/wpn_base_upgraded
{
	{
		map models/weapons/auto_rifles/g43/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .13
				tcMod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}



models/weapons/assault_rifles/mp44/wpn_base
{
	{
		map models/weapons/assault_rifles/mp44/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .14
                tcMod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/assault_rifles/mp44/wpn_base_upgraded
{
	{
		map models/weapons/assault_rifles/mp44/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .14
                tcMod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}



models/weapons/smgs/thompson/wpn_base
{
	{
		map models/weapons/smgs/thompson/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .10
                tcMod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
}


models/weapons/smgs/thompson/wpn_base_upgraded
{
	{
		map models/weapons/smgs/thompson/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .10
                tcMod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}


models/weapons/smgs/sten/wpn_base
{
	{
		map models/weapons/smgs/sten/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.3 1.3
		rgbGen lightingDiffuse
        }
}

models/weapons/smgs/sten/wpn_base_upgraded
{
	{
		map models/weapons/smgs/sten/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.3 1.3
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/smgs/sten/wpn_base2
{
	{
		map models/weapons/smgs/sten/wpn_base2.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.3 1.3
		rgbGen lightingDiffuse
        }
}

models/weapons/smgs/sten/wpn_base2_upgraded
{
	{
		map models/weapons/smgs/sten/wpn_base2.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
		tcGen environment
                tcMod scale 1.3 1.3
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}

models/weapons/pistols/tt33/wpn_base
{
	{
		map models/weapons/pistols/tt33/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
				tcmod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
}

models/weapons/pistols/tt33/wpn_base_upgraded
{
	{
		map models/weapons/pistols/tt33/wpn_base.jpg
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/envmap_slateH.tga
		blendFunc GL_SRC_ALPHA GL_ONE
                alphaGen const .1
				tcmod scale 1.2 1.2
		tcGen environment
		rgbGen lightingDiffuse
        }
		
				{
        map textures/sfx/wpn_upgrade_1.tga 
        blendFunc GL_SRC_ALPHA GL_ONE 
        rgbGen const ( 0.15 0.15 0.15 )
        tcGen environment 
        tcMod scroll 0.025 -0.07625
		tcMod scale 2.0 2.0
        }
}



models/powerups/ammo/amtesla
{
	{
		map textures/effects/specularB.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/powerups/ammo/amtesla.tga
		blendfunc blend
		rgbGen lightingDiffuse
	}
}

models/multiplayer/supplies/ammobox
{
	{
		map textures/effects/envmap_slate.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/multiplayer/supplies/ammobox.tga
		blendfunc blend
		rgbGen lightingDiffuse
	}
}




